### ISSUE TITLE
Повторное добавление атрибутов в регистратор

### ISSUE THREAD

**Issue by aaa2ppp** [GolangLessons/url-shortener#6]
Обработчики используют конструкцию:

https://github.com/GolangLessons/url-shortener/blob/b8c3104334ea137a777f784b16b3ff3962a5c3c8/internal/http-server/handlers/redirect/redirect.go#L28-L31

Несмотря на то, что _log_ является локальной для функции конструктора обработчика, она внешняя по отношению к самому обработчику и сохраняет состояние между вызовами обработчика. В результате атрибуты будут повторно добавляться в регистратор при каждом вызове обработчика.

Визуально проявление проблемы можно наблюдать, если для режима _local_ вместо _PrettySlog_ использовать стандартный _TextHandler_. При каждом обращении к серверу размер строк журнала будут расти из-за повтора атрибутов.

Для решения проблемы достаточно сделать переменную _log_ локальной, используя **`:=`**
`log := log.With(...)`

**Comment by justskiv** [comment]
Смержил PR, спасибо большое за помощь
